# Generated by Django 4.2.5 on 2023-10-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votecode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=100, null=True)),
                ('subvote', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjectcode', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('mname', models.CharField(max_length=100, null=True)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('check_number', models.CharField(max_length=20, null=True, unique=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('expected_retirement_date', models.DateField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.district')),
                ('education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.educationlevel')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.region')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.school')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.schoollevel')),
                ('subjects_taught', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.subject')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.userroles')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationType', models.CharField(choices=[('Exchange', 'Exchange'), ('Request', 'Request')], max_length=20)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('Reasons', models.TextField()),
                ('ApplicationDate', models.DateField()),
                ('SupportingDocuments', models.FileField(upload_to='supporting_documents/')),
                ('Comments', models.TextField(blank=True, null=True)),
                ('ApprovalStatus', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=20)),
                ('decision_date', models.DateField(auto_now=True, null=True)),
                ('FromDistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_district', to='tottmsappbeta.district')),
                ('RequestedDistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_district', to='tottmsappbeta.district')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher')),
                ('ToDistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_district', to='tottmsappbeta.district')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.TextField()),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='School_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.schoollevel'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.district'),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.region'),
        ),
        migrations.CreateModel(
            name='SalaryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.region')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('filled', models.BooleanField(default=False)),
                ('DistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.district')),
                ('RegionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.region')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.region'),
        ),
        migrations.CreateModel(
            name='ArrivingTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArrivalDate', models.DateField()),
                ('departure_date', models.DateField(auto_now=True, null=True)),
                ('AssignedSchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.school')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher')),
            ],
        ),
    ]
