# Generated by Django 4.2.5 on 2023-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('form', models.FileField(upload_to='forms/')),
            ],
        ),
    ]
