# Generated by Django 4.2.5 on 2023-10-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0002_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='expected_retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
