# Generated by Django 4.2.5 on 2023-10-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0004_gender_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
    ]
