# Generated by Django 4.2.5 on 2023-10-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0005_remove_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.position'),
        ),
    ]
