# Generated by Django 4.2.5 on 2023-10-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0006_teacher_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
    ]
