# Generated by Django 4.2.5 on 2023-10-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0010_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transferapplication',
            name='Reasons_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.transferreasons'),
        ),
    ]
