# Generated by Django 4.2.5 on 2023-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0012_remove_transferapplication_requesteddistrictid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
