# Generated by Django 4.2.5 on 2023-11-12 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0013_alter_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nin',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999999999999), django.core.validators.MinValueValidator(10000000000000000000)]),
        ),
    ]
