# Generated by Django 4.2.5 on 2023-11-12 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0018_alter_teacher_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxValueValidator(99999999999999999999), django.core.validators.MinValueValidator(10000000000000000000)]),
        ),
    ]
