# Generated by Django 4.2.5 on 2023-11-12 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0019_alter_teacher_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=20), django.core.validators.MinLengthValidator(limit_value=20)]),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='ApplicationType',
            field=models.CharField(choices=[('Exchange', 'Exchange'), ('Request', 'Request')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='ApprovalStatus',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='Reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='SupportingDocuments',
            field=models.FileField(blank=True, null=True, upload_to='supporting_documents/'),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='TeacherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tottmsappbeta.teacher'),
        ),
    ]
