# Generated by Django 4.2.5 on 2023-11-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0020_alter_teacher_nin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferapplication',
            name='ApplicationType',
            field=models.CharField(blank=True, choices=[('Exchange', 'Exchange'), ('Request', 'Request')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='ApprovalStatus',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
