# Generated by Django 4.2.5 on 2023-11-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0021_alter_transferapplication_applicationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
