# Generated by Django 4.2.5 on 2023-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottmsappbeta', '0022_transferapplication_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
